# Generated by Django 6.0 on 2025-12-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('has_statics', models.BooleanField(default=False)),
                ('has_cashbox', models.BooleanField(default=False)),
                ('has_invoices', models.BooleanField(default=False)),
                ('has_personal_accounts', models.BooleanField(default=False)),
                ('has_apartaments', models.BooleanField(default=False)),
                ('has_owners', models.BooleanField(default=False)),
                ('has_messages', models.BooleanField(default=False)),
                ('has_master_requests', models.BooleanField(default=False)),
                ('has_meters', models.BooleanField(default=False)),
                ('has_site_managment', models.BooleanField(default=False)),
                ('has_services', models.BooleanField(default=False)),
                ('has_tariffs', models.BooleanField(default=False)),
                ('has_roles', models.BooleanField(default=False)),
                ('has_users', models.BooleanField(default=False)),
                ('has_payment_details', models.BooleanField(default=False)),
            ],
        ),
    ]
