# Generated by Django 5.1.4 on 2026-01-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='house',
        ),
    ]
