# Generated by Django 6.0 on 2026-01-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_managers_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Приход'), ('new', 'Расход'), ('inactive', 'Отключенный')], default='active'),
        ),
    ]
