# Generated by Django 6.0 on 2026-01-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='second_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
