# Generated by Django 6.0 on 2026-01-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_name_user_second_name_remove_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Активные'), ('new', 'Новые'), ('inactive', 'Отключенный')], default='active'),
        ),
    ]
