# Generated by Django 5.1.4 on 2026-02-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='has_apartaments',
            new_name='has_apartments',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='has_site_managment',
            new_name='has_site_management',
        ),
    ]
