# Generated by Django 5.1.4 on 2026-02-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_has_apartaments_role_has_apartments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
