# Generated by Django 5.1.4 on 2026-02-20 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='has_statics',
            new_name='has_statistics',
        ),
    ]
