# Generated by Django 5.1.4 on 2026-02-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_has_statics_role_has_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='has_housess',
            field=models.BooleanField(default=False),
        ),
    ]
