# Generated by Django 5.1.4 on 2026-02-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_role_has_housess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='has_housess',
            new_name='has_article',
        ),
        migrations.AddField(
            model_name='role',
            name='has_houses',
            field=models.BooleanField(default=False),
        ),
    ]
