# Generated by Django 5.1.4 on 2026-03-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_email_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Активные'), ('new', 'Новые'), ('inactive', 'Отключенный')], default='new'),
        ),
    ]
