# Generated by Django 6.0 on 2025-12-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_showing',
            field=models.BooleanField(default=False, verbose_name='Показывать'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='unitsofmeasurement',
            name='units',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
