# Generated by Django 5.1.4 on 2026-03-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_article_id_alter_requisite_id_alter_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='units_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.unitsofmeasurement'),
        ),
        migrations.AlterField(
            model_name='servicescost',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.service'),
        ),
        migrations.AlterField(
            model_name='servicescost',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='settings.tariffs'),
        ),
        migrations.AlterUniqueTogether(
            name='servicescost',
            unique_together={('tariff', 'service')},
        ),
    ]
