# Generated by Django 6.0 on 2025-12-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_service_description_alter_service_is_showing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход')])),
            ],
        ),
    ]
