# Generated by Django 6.0 on 2026-01-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_tariffs_servicescost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
