# Generated by Django 5.1.4 on 2026-01-11 19:45

import ckeditor.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsAndSeoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_text', ckeditor.fields.RichTextField()),
                ('extra_title', models.CharField(max_length=200)),
                ('extra_short_text', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('about_us_and_seo_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.aboutusandseoblock')),
            ],
        ),
        migrations.AddField(
            model_name='aboutusandseoblock',
            name='extra_gallery',
            field=models.ManyToManyField(related_name='about_us_extra_gallery', to='managements.images'),
        ),
        migrations.AddField(
            model_name='aboutusandseoblock',
            name='gallery',
            field=models.ManyToManyField(related_name='about_us_gallery', to='managements.images'),
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1', models.ImageField(upload_to='slides/')),
                ('slide2', models.ImageField(upload_to='slides/')),
                ('slide3', models.ImageField(upload_to='slides/')),
                ('title', models.CharField(max_length=200)),
                ('short_text', ckeditor.fields.RichTextField()),
                ('block_image_1', models.ImageField(upload_to='slides/')),
                ('block_title_1', models.CharField(max_length=200)),
                ('block_description_1', ckeditor.fields.RichTextField()),
                ('block_image_2', models.ImageField(upload_to='slides/')),
                ('block_title_2', models.CharField(max_length=200)),
                ('block_description_2', ckeditor.fields.RichTextField()),
                ('block_image_3', models.ImageField(upload_to='slides/')),
                ('block_title_3', models.CharField(max_length=200)),
                ('block_description_3', ckeditor.fields.RichTextField()),
                ('block_image_4', models.ImageField(upload_to='slides/')),
                ('block_title_4', models.CharField(max_length=200)),
                ('block_description_4', ckeditor.fields.RichTextField()),
                ('block_image_5', models.ImageField(upload_to='slides/')),
                ('block_title_5', models.CharField(max_length=200)),
                ('block_description_5', ckeditor.fields.RichTextField()),
                ('block_image_6', models.ImageField(upload_to='slides/')),
                ('block_title_6', models.CharField(max_length=200)),
                ('block_description_6', ckeditor.fields.RichTextField()),
                ('is_link', models.BooleanField(blank=True, default=False)),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_text', ckeditor.fields.RichTextField()),
                ('link_site', models.URLField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('map_fragment', models.TextField()),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.seoblock')),
            ],
        ),
        migrations.AddField(
            model_name='aboutusandseoblock',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.seoblock'),
        ),
        migrations.CreateModel(
            name='ServicesAndSeoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesForSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('services_and_seo_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.servicesandseoblock')),
            ],
        ),
        migrations.CreateModel(
            name='TariffsAndSeoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_text', ckeditor.fields.RichTextField()),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='TariffsForSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tariffs/')),
                ('tariffs_and_seo_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.tariffsandseoblock')),
            ],
        ),
    ]
