# Generated by Django 6.0 on 2025-12-21 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1', models.ImageField(upload_to='slides/')),
                ('slide2', models.ImageField(upload_to='slides/')),
                ('slide3', models.ImageField(upload_to='slides/')),
                ('title', models.CharField(max_length=200)),
                ('short_text', models.TextField()),
                ('block_image_1', models.ImageField(upload_to='slides/')),
                ('block_title_1', models.CharField(max_length=200)),
                ('block_description_1', models.TextField()),
                ('block_image_2', models.ImageField(upload_to='slides/')),
                ('block_title_2', models.CharField(max_length=200)),
                ('block_description_2', models.TextField()),
                ('block_image_3', models.ImageField(upload_to='slides/')),
                ('block_title_3', models.CharField(max_length=200)),
                ('block_description_3', models.TextField()),
                ('block_image_4', models.ImageField(upload_to='slides/')),
                ('block_title_4', models.CharField(max_length=200)),
                ('block_description_4', models.TextField()),
                ('block_image_5', models.ImageField(upload_to='slides/')),
                ('block_title_5', models.CharField(max_length=200)),
                ('block_description_5', models.TextField()),
                ('block_image_6', models.ImageField(upload_to='slides/')),
                ('block_title_6', models.CharField(max_length=200)),
                ('block_description_6', models.TextField()),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.seoblock')),
            ],
        ),
    ]
