# Generated by Django 6.0 on 2025-12-21 00:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='short_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
