# Generated by Django 6.0 on 2025-12-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_alter_mainpage_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='is_link',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
