# Generated by Django 6.0 on 2025-12-22 00:46

import ckeditor.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_mainpage_is_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_2',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_3',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_4',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_5',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='block_description_6',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_text', ckeditor.fields.RichTextField()),
                ('link_site', models.URLField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_address', models.EmailField(max_length=254)),
                ('map_fragment', models.TextField()),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.seoblock')),
            ],
        ),
    ]
