# Generated by Django 6.0 on 2025-12-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_alter_mainpage_block_description_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='email_address',
        ),
    ]
