# Generated by Django 6.0 on 2025-12-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0005_remove_contacts_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
