# Generated by Django 6.0 on 2025-12-22 16:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0006_contacts_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesAndSeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesForSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', ckeditor.fields.RichTextField()),
                ('services_and_seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.servicesandseoblock')),
            ],
        ),
    ]
