# Generated by Django 6.0 on 2025-12-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0007_servicesandseoblock_servicesforsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesforsite',
            name='services_and_seo_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.servicesandseoblock'),
        ),
        migrations.CreateModel(
            name='TariffsAndSeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='TariffsForSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='tariffs/')),
                ('tariffs_and_seo_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.tariffsandseoblock')),
            ],
        ),
    ]
