# Generated by Django 6.0 on 2025-12-23 19:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0008_alter_servicesforsite_services_and_seo_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesforsite',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicesforsite',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicesforsite',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
