# Generated by Django 6.0 on 2025-12-23 21:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0010_alter_servicesforsite_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffsandseoblock',
            name='short_text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariffsandseoblock',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tariffsforsite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tariffs/'),
        ),
        migrations.AlterField(
            model_name='tariffsforsite',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
