# Generated by Django 6.0 on 2025-12-24 01:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0011_tariffsandseoblock_short_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsAndSeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_text', ckeditor.fields.RichTextField()),
                ('extra_title', models.CharField(max_length=200)),
                ('extra_short_text', ckeditor.fields.RichTextField()),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managements.seoblock')),
                ('extra_gallery', models.ManyToManyField(related_name='about_us_extra_gallery', to='managements.images')),
                ('gallery', models.ManyToManyField(related_name='about_us_gallery', to='managements.images')),
            ],
        ),
    ]
