# Generated by Django 6.0 on 2025-12-24 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0012_images_aboutusandseoblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('about_us_and_seo_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.aboutusandseoblock')),
            ],
        ),
    ]
