# Generated by Django 6.0 on 2025-12-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0013_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusandseoblock',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
