# Generated by Django 5.1.4 on 2026-01-13 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_rename_sector_section_house_owner_and_more'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('PAID', 'Оплачена'), ('PARTIALLY', 'Частично'), ('UNPAID', 'Неоплачен')], max_length=10)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.floor')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.house')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.section')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.tariffs')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('area', models.IntegerField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.floor')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.house')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.section')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.tariffs')),
            ],
        ),
    ]
