# Generated by Django 5.1.4 on 2026-01-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_bankbook_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
