# Generated by Django 5.1.4 on 2026-01-14 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_bankbook_number'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flat',
            new_name='Apartment',
        ),
        migrations.AddField(
            model_name='bankbook',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin.apartment'),
            preserve_default=False,
        ),
    ]
