# Generated by Django 5.1.4 on 2026-01-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_rename_flat_apartment_bankbook_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'Оплачена'), ('PARTIALLY', 'Частично'), ('UNPAID', 'Неоплачен')], max_length=10, null=True),
        ),
    ]
