# Generated by Django 5.1.4 on 2026-01-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_alter_bankbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Активен'), ('INACTIVE', 'Неактивен')], max_length=10, null=True),
        ),
    ]
