# Generated by Django 5.1.4 on 2026-01-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_remove_bankbook_owner_remove_bankbook_tariff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankbook',
            name='floor',
        ),
    ]
