# Generated by Django 5.1.4 on 2026-01-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_remove_bankbook_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='section',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to='admin.section'),
        ),
    ]
