# Generated by Django 5.1.4 on 2026-01-25 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0011_alter_apartment_owner_alter_apartment_section'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('TAKEN', 'Учтено'), ('TAKEN_AND_PAID', 'Учтено и оплочено'), ('NULLABLE', 'Нулевое')], default='NEW')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.apartment')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.house')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.section')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.service')),
            ],
        ),
    ]
