# Generated by Django 5.1.4 on 2026-01-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0012_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='readings',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
