# Generated by Django 5.1.4 on 2026-01-25 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0014_alter_apartment_floor_alter_apartment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin.apartment'),
        ),
    ]
