# Generated by Django 5.1.4 on 2026-01-26 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0015_alter_bankbook_apartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='created_at',
            new_name='date',
        ),
    ]
