# Generated by Django 5.1.4 on 2026-01-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0016_rename_created_at_counter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='date',
            field=models.DateField(),
        ),
    ]
