# Generated by Django 5.1.4 on 2026-01-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0017_alter_counter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
