# Generated by Django 5.1.4 on 2026-01-31 19:18

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0018_alter_apartment_area_alter_house_address_and_more'),
        ('settings', '0002_alter_article_id_alter_requisite_id_alter_service_id_and_more'),
        ('user', '0007_remove_user_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.tariffs'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.house'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.section'),
        ),
        migrations.CreateModel(
            name='MasterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('call_status', models.CharField(choices=[('NEW', 'Новое'), ('IN WORK', 'В работе'), ('COMPLETED', 'Выполнена')], default='NEW')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.apartment')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_set', to=settings.AUTH_USER_MODEL)),
                ('master_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.role')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
