# Generated by Django 5.1.4 on 2026-01-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0019_alter_apartment_tariff_alter_counter_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercall',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
