# Generated by Django 5.1.4 on 2026-01-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0020_alter_mastercall_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercall',
            name='master_type',
            field=models.CharField(choices=[('PL', 'Сантехник'), ('EL', 'Электрик'), ('LS', 'Слесарь'), ('ANY', 'Любой специалист')], default=1),
            preserve_default=False,
        ),
    ]
