# Generated by Django 5.1.4 on 2026-02-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0022_alter_mastercall_master_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercall',
            name='call_status',
            field=models.CharField(blank=True, choices=[('NEW', 'Новое'), ('IN WORK', 'В работе'), ('COMPLETED', 'Выполнена')], default='NEW', null=True),
        ),
    ]
