# Generated by Django 5.1.4 on 2026-02-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0023_alter_mastercall_call_status'),
        ('settings', '0002_alter_article_id_alter_requisite_id_alter_service_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PD', 'Оплачена'), ('PT', 'Частично оплачена'), ('UPD', 'Неоплачена')], max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.apartment')),
                ('bankbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.bankbook')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.house')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.section')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.service')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.tariffs')),
            ],
        ),
    ]
