# Generated by Django 5.1.4 on 2026-02-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0024_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_catch',
            field=models.BooleanField(default=True),
        ),
    ]
