# Generated by Django 5.1.4 on 2026-02-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0025_receipt_is_catch'),
        ('settings', '0002_alter_article_id_alter_requisite_id_alter_service_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFullCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_cost', models.FloatField(blank=True, null=True)),
                ('Consumption', models.FloatField(blank=True, null=True)),
                ('service_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.service')),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.servicefullcost'),
        ),
    ]
