# Generated by Django 5.1.4 on 2026-02-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0026_servicefullcost_alter_receipt_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicefullcost',
            old_name='service_cost',
            new_name='service',
        ),
        migrations.AddField(
            model_name='servicefullcost',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
