# Generated by Django 5.1.4 on 2026-02-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0027_rename_service_cost_servicefullcost_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicefullcost',
            old_name='Consumption',
            new_name='consumption',
        ),
    ]
