# Generated by Django 5.1.4 on 2026-02-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0028_rename_consumption_servicefullcost_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='service',
        ),
        migrations.AddField(
            model_name='servicefullcost',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin.receipt'),
            preserve_default=False,
        ),
    ]
