# Generated by Django 5.1.4 on 2026-02-04 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0029_remove_receipt_service_servicefullcost_receipt'),
        ('settings', '0002_alter_article_id_alter_requisite_id_alter_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefullcost',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.unitsofmeasurement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('PD', 'Оплачена'), ('PT', 'Частично оплачена'), ('UPD', 'Неоплачена')], default='UPD', max_length=10),
        ),
    ]
