# Generated by Django 5.1.4 on 2026-02-07 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0031_message_messagestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin.apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.floor'),
        ),
        migrations.AddField(
            model_name='message',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin.house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.section'),
        ),
    ]
