# Generated by Django 5.1.4 on 2026-02-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0032_message_apartment_message_floor_message_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='for_debtor',
            field=models.BooleanField(default=False),
        ),
    ]
