# Generated by Django 5.1.4 on 2026-02-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0033_message_for_debtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='message',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='for_debtor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='house',
        ),
        migrations.RemoveField(
            model_name='message',
            name='section',
        ),
    ]
