# Generated by Django 5.1.4 on 2026-02-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0034_remove_message_apartment_remove_message_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
