# Generated by Django 5.1.4 on 2026-02-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0037_message_apartment_message_floor_message_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XlsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('template', models.FilePathField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
