# Generated by Django 5.1.4 on 2026-02-11 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0038_xlstemplate'),
        ('settings', '0002_alter_article_id_alter_requisite_id_alter_service_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('number', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.article')),
                ('bank_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.bankbook')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_manager_set', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocashbox_wner_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
