# Generated by Django 5.1.4 on 2026-02-11 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0039_cashbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='is_catch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.receipt'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_owner_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
