# Generated by Django 5.1.4 on 2026-02-11 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0040_cashbox_is_catch_cashbox_receipt_alter_cashbox_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.apartment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.floor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.house'),
        ),
    ]
