# Generated by Django 5.1.4 on 2026-02-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0042_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbox',
            old_name='summ',
            new_name='sum',
        ),
        migrations.AddField(
            model_name='cashbox',
            name='status',
            field=models.CharField(blank=True, choices=[('CM', 'Приход'), ('OG', 'Расход')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новое'), ('TAKEN', 'Учтено'), ('TAKEN_AND_PAID', 'Учтено и оплачено'), ('NULLABLE', 'Нулевое')], default='NEW'),
        ),
    ]
