# Generated by Django 5.1.4 on 2026-02-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0043_rename_summ_cashbox_sum_cashbox_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='counter_ids',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='ID счетчиков'),
        ),
    ]
