# Generated by Django 5.1.4 on 2026-02-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0044_receipt_counter_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.receipt'),
        ),
    ]
