# Generated by Django 5.1.4 on 2026-02-17 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0045_alter_cashbox_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.apartment'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.house'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.section'),
        ),
    ]
