# Generated by Django 5.1.4 on 2026-02-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0046_alter_bankbook_apartment_alter_bankbook_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Активен'), ('INACTIVE', 'Неактивен')], default='ACTIVE', max_length=10, null=True),
        ),
    ]
