# Generated by Django 5.1.4 on 2026-02-21 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0047_alter_bankbook_status'),
        ('user', '0012_rename_has_housess_role_has_article_role_has_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercall',
            name='master_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.role'),
        ),
    ]
