# Generated by Django 5.1.4 on 2026-03-01 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0048_alter_mastercall_master_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlstemplate',
            name='template',
            field=models.FileField(upload_to='templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])]),
        ),
    ]
