# Generated by Django 5.1.4 on 2026-03-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0049_alter_xlstemplate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='number',
            field=models.CharField(),
        ),
    ]
