# Generated by Django 5.1.4 on 2026-03-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0050_alter_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='number',
            field=models.CharField(max_length=11),
        ),
    ]
