# Generated by Django 5.1.4 on 2026-03-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin', '0051_alter_receipt_number'),
        ('settings', '0002_alter_article_id_alter_requisite_id_alter_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='number',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin.apartment'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='bankbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='admin.bankbook'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='admin.section'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='settings.tariffs'),
        ),
    ]
