# Generated by Django 5.1.4 on 2026-03-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0052_mastercall_created_at_alter_bankbook_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercall',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
