# Generated by Django 5.1.4 on 2026-03-05 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0054_alter_mastercall_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.ManyToManyField(limit_choices_to={'is_staff': True}, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
